export interface Research {
  id: string;
  name: string;
  cost: number;
  requires: string[];
  effect: string;
  boost: string;
}
const tree = (rows: string[][]): Research[] =>
  rows.map(([id, name, cost, requires, effect, boost]) => ({
    id,
    name,
    cost: Number(cost),
    requires: requires ? requires.split(",") : [],
    effect,
    boost,
  }));
export const techs = tree([
  ["pottery", "制陶术", "20", "", "粮仓", "建立城市"],
  ["mining", "采矿业", "20", "", "矿山", "发现丘陵"],
  ["animals", "畜牧业", "20", "", "牧场", "发现牲畜"],
  ["writing", "文字", "40", "pottery", "学院、图书馆", "遇见其他文明"],
  ["archery", "弓箭", "35", "animals", "弓箭手", "击败敌军"],
  ["masonry", "砌砖", "45", "mining", "城墙", "建造矿山"],
  ["bronze", "青铜器", "55", "mining", "剑士", "击败两支敌军"],
  ["currency", "货币", "65", "writing", "商业中心、市场", "建立贸易路线"],
  ["engineering", "工程", "80", "masonry", "水渠", "建造城墙"],
  ["education", "教育", "110", "writing,currency", "大学", "拥有两座学院"],
  ["machinery", "机械", "100", "engineering,archery", "弩手", "拥有三支军队"],
  [
    "industry",
    "工业化",
    "160",
    "education,machinery",
    "工业区、工厂",
    "拥有三个矿山",
  ],
  ["flight", "飞行", "200", "industry", "旅游业翻倍", "建造奇观"],
  ["rocketry", "火箭研究", "250", "flight", "航天中心", "拥有大学"],
  ["satellites", "卫星", "300", "rocketry", "发射卫星", "建造航天中心"],
  ["robotics", "机器人技术", "400", "satellites", "火星殖民", "发射卫星"],
]);
export const civics = tree([
  ["laws", "法典", "15", "", "酋邦、纪律、城市规划", "建立城市"],
  ["craft", "技艺", "30", "laws", "劳役、农业政策", "改良三个地块"],
  ["trade", "对外贸易", "35", "laws", "商队", "遇见其他文明"],
  [
    "empire",
    "帝国初期",
    "50",
    "craft,trade",
    "殖民政策、边界扩张",
    "总人口达到六",
  ],
  [
    "philosophy",
    "政治哲学",
    "70",
    "empire",
    "古典共和、寡头政体",
    "拥有三座城市",
  ],
  ["drama", "戏剧与诗歌", "70", "empire", "剧院广场", "建造奇观"],
  ["theology", "神学", "100", "drama", "圣地、传教士", "创立宗教"],
  ["feudal", "封建主义", "120", "philosophy", "农奴制", "拥有六座农场"],
  [
    "exploration",
    "探索",
    "170",
    "feudal,trade",
    "商人共和国",
    "拥有两条贸易路线",
  ],
  ["humanism", "人文主义", "170", "drama,philosophy", "博物馆", "拥有两座剧院"],
  [
    "democracy",
    "民主主义",
    "250",
    "exploration,humanism",
    "民主政体",
    "总人口达到二十",
  ],
  ["media", "大众传媒", "300", "democracy", "文化胜利", "旅游达到一百"],
]);
export interface Item {
  id: string;
  name: string;
  cost: number;
  kind: "unit" | "building" | "district" | "wonder" | "project";
  unlock?: string;
  needs?: string;
  description: string;
  icon: string;
  strength?: number;
  moves?: number;
  range?: number;
}
export const items: Item[] = [
  {
    id: "settler",
    name: "开拓者",
    cost: 50,
    kind: "unit",
    description: "建立新城市，消耗一人口",
    icon: "⚑",
    moves: 2,
  },
  {
    id: "scout",
    name: "侦察兵",
    cost: 20,
    kind: "unit",
    description: "探索地图",
    icon: "♧",
    strength: 10,
    moves: 3,
  },
  {
    id: "warrior",
    name: "勇士",
    cost: 30,
    kind: "unit",
    description: "近战单位",
    icon: "⚔",
    strength: 20,
    moves: 2,
  },
  {
    id: "builder",
    name: "建造者",
    cost: 25,
    kind: "unit",
    description: "三次改良地块",
    icon: "⚒",
    moves: 2,
  },
  {
    id: "archer",
    name: "弓箭手",
    cost: 40,
    kind: "unit",
    unlock: "archery",
    description: "两格远程攻击",
    icon: "➶",
    strength: 25,
    moves: 2,
    range: 2,
  },
  {
    id: "sword",
    name: "剑士",
    cost: 65,
    kind: "unit",
    unlock: "bronze",
    description: "需要铁资源",
    icon: "⚔",
    strength: 36,
    moves: 2,
  },
  {
    id: "crossbow",
    name: "弩手",
    cost: 85,
    kind: "unit",
    unlock: "machinery",
    description: "两格远程攻击",
    icon: "➶",
    strength: 45,
    moves: 2,
    range: 2,
  },
  {
    id: "missionary",
    name: "传教士",
    cost: 70,
    kind: "unit",
    unlock: "theology",
    description: "三次传播信仰",
    icon: "☼",
    moves: 3,
  },
  {
    id: "monument",
    name: "纪念碑",
    cost: 25,
    kind: "building",
    description: "文化 +2",
    icon: "▥",
  },
  {
    id: "granary",
    name: "粮仓",
    cost: 30,
    kind: "building",
    unlock: "pottery",
    description: "粮食 +1，住房 +2",
    icon: "♜",
  },
  {
    id: "walls",
    name: "远古城墙",
    cost: 45,
    kind: "building",
    unlock: "masonry",
    description: "城市防御 +15",
    icon: "▤",
  },
  {
    id: "campus",
    name: "学院",
    cost: 45,
    kind: "district",
    unlock: "writing",
    description: "科技 +2，每座相邻山脉额外 +1",
    icon: "⚗",
  },
  {
    id: "library",
    name: "图书馆",
    cost: 35,
    kind: "building",
    needs: "campus",
    description: "科技 +2",
    icon: "▥",
  },
  {
    id: "university",
    name: "大学",
    cost: 80,
    kind: "building",
    unlock: "education",
    needs: "campus",
    description: "科技 +4",
    icon: "⚗",
  },
  {
    id: "commercial",
    name: "商业中心",
    cost: 55,
    kind: "district",
    unlock: "currency",
    description: "金币 +4，贸易容量 +1",
    icon: "¤",
  },
  {
    id: "market",
    name: "市场",
    cost: 40,
    kind: "building",
    needs: "commercial",
    description: "金币 +3",
    icon: "¤",
  },
  {
    id: "aqueduct",
    name: "水渠",
    cost: 55,
    kind: "building",
    unlock: "engineering",
    description: "住房 +4",
    icon: "≈",
  },
  {
    id: "theater",
    name: "剧院广场",
    cost: 55,
    kind: "district",
    unlock: "drama",
    description: "文化 +3，旅游 +2",
    icon: "♫",
  },
  {
    id: "museum",
    name: "博物馆",
    cost: 100,
    kind: "building",
    unlock: "humanism",
    needs: "theater",
    description: "文化 +3，旅游 +6",
    icon: "♫",
  },
  {
    id: "holy",
    name: "圣地",
    cost: 55,
    kind: "district",
    unlock: "theology",
    description: "信仰 +4，相邻山脉额外 +1",
    icon: "☼",
  },
  {
    id: "industrial",
    name: "工业区",
    cost: 85,
    kind: "district",
    unlock: "industry",
    description: "生产 +4，相邻矿山额外 +1",
    icon: "⚙",
  },
  {
    id: "factory",
    name: "工厂",
    cost: 100,
    kind: "building",
    needs: "industrial",
    description: "生产 +5",
    icon: "⚙",
  },
  {
    id: "pyramids",
    name: "金字塔",
    cost: 100,
    kind: "wonder",
    unlock: "masonry",
    description: "所有建造者次数 +1，文化 +3",
    icon: "△",
  },
  {
    id: "libraryWonder",
    name: "大图书馆",
    cost: 140,
    kind: "wonder",
    unlock: "education",
    description: "科技 +8",
    icon: "▥",
  },
  {
    id: "spaceport",
    name: "航天中心",
    cost: 180,
    kind: "district",
    unlock: "rocketry",
    description: "开启太空项目，不占区域容量",
    icon: "↟",
  },
  {
    id: "satellite",
    name: "发射卫星",
    cost: 200,
    kind: "project",
    unlock: "satellites",
    needs: "spaceport",
    description: "科学胜利第一阶段",
    icon: "✧",
  },
  {
    id: "mars",
    name: "火星殖民",
    cost: 300,
    kind: "project",
    unlock: "robotics",
    needs: "satellite",
    description: "科学胜利",
    icon: "✧",
  },
];
export const policies = [
  {
    id: "planning",
    name: "城市规划",
    unlock: "laws",
    description: "每城生产 +1",
  },
  {
    id: "discipline",
    name: "纪律",
    unlock: "laws",
    description: "军队战斗力 +5",
  },
  {
    id: "labor",
    name: "劳役",
    unlock: "craft",
    description: "建筑与区域生产 +30%",
  },
  {
    id: "colonial",
    name: "殖民",
    unlock: "empire",
    description: "开拓者生产 +50%",
  },
  {
    id: "serfdom",
    name: "农奴制",
    unlock: "feudal",
    description: "新建造者次数 +2",
  },
  {
    id: "rational",
    name: "理性主义",
    unlock: "humanism",
    description: "科技 +25%",
  },
];
export const governments = [
  { id: "chief", name: "酋邦", unlock: "", slots: 2 },
  { id: "republic", name: "古典共和", unlock: "philosophy", slots: 3 },
  { id: "oligarchy", name: "寡头政体", unlock: "philosophy", slots: 3 },
  { id: "merchant", name: "商人共和国", unlock: "exploration", slots: 4 },
  { id: "democracy", name: "民主政体", unlock: "democracy", slots: 5 },
];
